#include <glad/gl.h>
#include "core/Application.h"
#include "core/GameState.h"
#include "utils/Raycaster.h"
#include <glm/gtc/matrix_transform.hpp>
#include <cstdlib>
#include <filesystem>
#include <fstream>
#include <iostream>
#include <stdexcept>
#define CHECK(x) do{if(!(x))throw std::runtime_error(std::to_string(__LINE__)+": " #x);}while(false)
struct MenusApplicationTests {
 static void press(Application& a,int code){a.routeInput(code,GLFW_PRESS);a.routeInput(code,GLFW_RELEASE);}
 static void snapshot(Application& a,const std::filesystem::path& folder,const std::string& name,int scale){
   int width=1280*scale,height=720*scale;GLuint fbo,color,depth;glGenFramebuffers(1,&fbo);glBindFramebuffer(GL_FRAMEBUFFER,fbo);glGenRenderbuffers(1,&color);glBindRenderbuffer(GL_RENDERBUFFER,color);glRenderbufferStorage(GL_RENDERBUFFER,GL_RGB8,width,height);glFramebufferRenderbuffer(GL_FRAMEBUFFER,GL_COLOR_ATTACHMENT0,GL_RENDERBUFFER,color);glGenRenderbuffers(1,&depth);glBindRenderbuffer(GL_RENDERBUFFER,depth);glRenderbufferStorage(GL_RENDERBUFFER,GL_DEPTH_COMPONENT24,width,height);glFramebufferRenderbuffer(GL_FRAMEBUFFER,GL_DEPTH_ATTACHMENT,GL_RENDERBUFFER,depth);CHECK(glCheckFramebufferStatus(GL_FRAMEBUFFER)==GL_FRAMEBUFFER_COMPLETE);glViewport(0,0,width,height);glClear(GL_COLOR_BUFFER_BIT|GL_DEPTH_BUFFER_BIT);
   if(a.m_chatOpen){a.m_renderer->drawMenu(a.chatView(),a.m_menuController,width,height);}else if(a.m_menu==Application::MenuState::Gameplay){auto pos=a.m_camera.position(a.m_player,a.m_world);auto proj=glm::perspective(glm::radians(a.m_camera.fov),width/static_cast<float>(height),.1f,500.f);a.m_renderer->draw(a.m_world,a.m_player,a.m_mobs,a.m_camera.isThirdPerson(),0,false,0,a.m_camera.view(a.m_player,pos),proj,pos,RayHit{},width,height,"CAMERA VERIFICATION",a.m_inventory,false,false,0,0,0,a.m_dayNight);}else a.m_renderer->drawMenu(a.menuView(),a.m_menuController,width,height);
   glFinish();CHECK(glGetError()==GL_NO_ERROR);std::vector<unsigned char> pixels(width*height*3);glReadBuffer(GL_COLOR_ATTACHMENT0);glPixelStorei(GL_PACK_ALIGNMENT,1);glReadPixels(0,0,width,height,GL_RGB,GL_UNSIGNED_BYTE,pixels.data());if(!folder.empty()){std::filesystem::create_directories(folder);std::ofstream out(folder/(name+"-"+std::to_string(scale)+".ppm"),std::ios::binary);out<<"P6\n"<<width<<' '<<height<<"\n255\n";for(int y=height-1;y>=0;--y)out.write(reinterpret_cast<char*>(pixels.data()+y*width*3),width*3);}glBindFramebuffer(GL_FRAMEBUFFER,0);glDeleteRenderbuffers(1,&color);glDeleteRenderbuffers(1,&depth);glDeleteFramebuffers(1,&fbo);
 }
 static void exercise(const std::filesystem::path& output){Application a(false);CHECK(!a.m_sessionActive&&a.m_menu==Application::MenuState::Title&&!a.m_captured);CHECK(a.m_repository.list().empty());a.saveGameState();CHECK(a.m_repository.list().empty());press(a,256);CHECK(a.m_menu==Application::MenuState::Title);
  for(int scale:{1,2})snapshot(a,output,"title",scale);
  a.activate(1);CHECK(a.m_menu==Application::MenuState::Worlds);a.activate(5);a.m_worldName.set("Test world");a.m_seedText.set("17");for(int scale:{1,2})snapshot(a,output,"create",scale);a.activate(23);CHECK(a.m_sessionActive&&a.m_world.seed()==17&&a.m_captured);WorldInfo first=a.m_activeWorld;a.m_world.setTaskBudgets(0,0,0);a.m_player.position={500,8,500};a.m_world.setBlock(500,7,497,BlockType::FURNACE);a.m_inventory.setHotbarSlot(0,ItemStack::block(BlockType::STONE,8));ItemStack cursor=ItemStack::food(FoodType::RAW_BEEF,3);CHECK(a.m_world.interactFurnace({500,7,497},FurnaceSlot::Input,cursor));cursor=ItemStack::block(BlockType::PLANKS,3);CHECK(a.m_world.interactFurnace({500,7,497},FurnaceSlot::Fuel,cursor));a.updateSimulation(1);auto progress=a.m_world.furnaceAt({500,7,497})->cookProgress;
  press(a,256);a.updateSimulation(2);CHECK(a.m_world.furnaceAt({500,7,497})->cookProgress==progress);a.activate(2);for(int scale:{1,2})snapshot(a,output,"settings",scale);a.slider(33,.5f);CHECK(a.m_settings.mouseSensitivity==.51f);a.activate(8);for(int scale:{1,2})snapshot(a,output,"keybindings",scale);
  // Capture ignores activation, supports mouse buttons, cancellation and confirmed swaps.
  a.m_input.event(257,true);a.activate(100);CHECK(a.m_keybindCapture==0&&!a.m_captureReady);a.routeInput(1007,GLFW_PRESS);CHECK(a.m_keybindCapture==0);a.routeInput(1007,GLFW_RELEASE);a.routeInput(257,GLFW_RELEASE);a.routeInput(1007,GLFW_PRESS);a.routeInput(1007,GLFW_RELEASE);CHECK(a.m_settings.key(KeyAction::MoveForward)==1007);a.activate(101);press(a,256);CHECK(a.m_settings.key(KeyAction::MoveBackward)==83);
  a.bind(0,83);CHECK(a.m_menu==Application::MenuState::Swap);for(int scale:{1,2})snapshot(a,output,"swap",scale);a.activate(0);CHECK(a.m_settings.key(KeyAction::MoveForward)==1007);a.bind(0,83);a.activate(12);CHECK(a.m_settings.key(KeyAction::MoveForward)==83&&a.m_settings.key(KeyAction::MoveBackward)==1007);a.activate(10);CHECK(a.m_settings.key(KeyAction::MoveForward)==87&&a.m_settings.mouseSensitivity==.51f);
  a.setMenu(Application::MenuState::Gameplay);a.routeInput(87,GLFW_PRESS);a.input(.1f);CHECK(glm::length(a.m_player.velocity)>0);press(a,256);press(a,256);a.input(.1f);CHECK(a.m_player.velocity.x==0&&a.m_player.velocity.z==0);a.routeInput(87,GLFW_RELEASE);a.routeInput(87,GLFW_PRESS);a.input(.1f);CHECK(glm::length(a.m_player.velocity)>0);a.routeInput(87,GLFW_RELEASE);
  a.routeInput(87,GLFW_PRESS);Application::focus(a.m_window,0);CHECK(a.m_menu==Application::MenuState::Pause&&!a.m_input.held(a.m_settings,KeyAction::MoveForward));a.routeInput(87,GLFW_RELEASE);a.setMenu(Application::MenuState::Gameplay);
  a.m_player.position={500,7,500};a.m_player.yaw=-90;a.m_player.pitch=-15;
  CHECK(a.m_settings.assign(KeyAction::Use,80));press(a,80);CHECK(a.m_furnaceOpen);press(a,256);
  CHECK(a.m_settings.assign(KeyAction::Attack,82));a.m_player.setGameMode(GameMode::Creative);a.m_world.setBlock(500,8,497,BlockType::STONE);auto hit=Raycaster::cast(a.m_world,a.m_player.eyePosition(),a.m_player.forward(),6);CHECK(hit.hit&&hit.block==glm::ivec3(500,8,497));a.m_player.setMiningTarget(hit.block);a.m_menuMouseReleaseRequired=false;a.routeInput(82,GLFW_PRESS);a.updateMining(.05f,a.m_player.eyePosition(),a.m_player.forward(),hit);a.routeInput(82,GLFW_RELEASE);CHECK(a.m_world.getBlock(500,8,497)==BlockType::AIR);a.m_settings.resetBindings();
  {DropSystem drops;World w;w.setBlock(20,6,20,BlockType::STONE);w.setBlock(20,7,20,BlockType::AIR);auto tool=ItemStack::tool(ToolKind::PICKAXE,ToolTier::STONE,37);CHECK(drops.tryThrow({20.5f,7.125f,20.5f},{0,0,0},tool,w));int collected=0;auto pickup=[&](const ItemStack& s){CHECK(s.kind==ItemKind::TOOL&&s.durability==37);++collected;return true;};for(int i=0;i<74;++i)drops.update(.01f,w,{20.5f,7.125f,20.5f},pickup);CHECK(collected==0);drops.update(.02f,w,{20.5f,7.125f,20.5f},pickup);CHECK(collected==1);for(int i=0;i<128;++i)CHECK(drops.tryThrow({20.5f,7.125f,20.5f},{0,0,0},tool,w));CHECK(!drops.tryThrow({20.5f,7.125f,20.5f},{0,0,0},tool,w)&&drops.activeCount()==128);}
  const float yaw=a.m_player.yaw;a.m_settings.mouseSensitivity=.2f;a.m_firstMouse=true;Application::cursor(a.m_window,100,100);CHECK(a.m_player.yaw==yaw);Application::cursor(a.m_window,110,100);CHECK(std::abs(a.m_player.yaw-yaw-2)<.001f);a.m_settings.invertY=true;const float pitch=a.m_player.pitch;Application::cursor(a.m_window,110,110);CHECK(std::abs(a.m_player.pitch-pitch-2)<.001f);
  a.m_player.yaw=-90;a.m_player.pitch=-15;a.m_player.position={500,7,500};a.m_player.setGameMode(GameMode::Creative);a.m_player.toggleFly();a.m_inventory.select(1);a.m_inventory.setBackpackSlot(0,ItemStack::block(BlockType::FURNACE,3));press(a,1002);CHECK(a.m_inventory.selectedStack().blockType==BlockType::FURNACE&&a.m_inventory.selectedStack().count==3&&a.m_inventory.backpackSlot(0).empty());int count=a.m_inventory.selectedStack().count;press(a,81);CHECK(a.m_inventory.selectedStack().count==count-1);press(a,290);CHECK(!a.m_hudVisible);a.routeInput(67,GLFW_PRESS);a.updateSimulation(1);CHECK(a.m_camera.fov<a.m_settings.baseFov*.36f);a.routeInput(67,GLFW_RELEASE);
  a.routeInput(84,GLFW_PRESS);Application::character(a.m_window,'t');CHECK(a.m_chatEntry.text.empty()&&a.m_chatOpen);a.routeInput(84,GLFW_RELEASE);Application::character(a.m_window,'w');CHECK(a.m_chatEntry.text=="w");a.message("Local messages stay in this world session.");for(int scale:{1,2})snapshot(a,output,"chat",scale);a.routeInput(87,GLFW_PRESS);a.input(.1f);CHECK(a.m_player.velocity.x==0&&a.m_player.velocity.z==0);a.routeInput(87,GLFW_RELEASE);progress=a.m_world.furnaceAt({500,7,497})->cookProgress;a.updateSimulation(1);CHECK(a.m_world.furnaceAt({500,7,497})->cookProgress>progress);press(a,256);
  auto pose=a.m_player.position;auto bed=a.m_player.spawnPosition();auto fuel=a.m_world.furnaceAt({500,7,497})->fuelRemaining;a.command("/tp nan 10 10");CHECK(a.m_player.position==pose);a.command("/tp 10 0 10");CHECK(a.m_player.position==pose);a.command("/gamemode creative invalid");CHECK(a.m_player.gameMode()==GameMode::Creative);a.command("/time set night");CHECK(a.m_dayNight.isNight()&&a.m_world.furnaceAt({500,7,497})->fuelRemaining==fuel);a.command("/tp 100 30 100");CHECK(a.m_player.position==glm::vec3(100,30,100)&&a.m_player.spawnPosition()==bed&&a.m_player.velocity==glm::vec3(0));a.command("/gamemode survival");CHECK(!a.m_player.isFlying);for(int i=0;i<120;++i)a.message("hello");CHECK(a.m_messages.size()==100);
  // Failure keeps the session and its data available.
  a.setMenu(Application::MenuState::Pause);auto path=SaveLoad::getSavePath().parent_path()/"worlds"/first.id/"save.dat.tmp";std::filesystem::create_directory(path);a.activate(9);CHECK(a.m_sessionActive&&a.m_menu==Application::MenuState::Pause);a.activate(9);CHECK(!a.m_sessionActive&&a.m_menu==Application::MenuState::Title);
  WorldInfo second;std::string error;CHECK(a.m_repository.create("Another world",18,GameMode::Creative,second,error));CHECK(a.enterWorld(second));CHECK(a.m_world.seed()==18&&a.m_inventory.hotbarSlot(0).empty()&&a.m_world.captureFurnaces().empty()&&a.m_messages.empty()&&a.m_commandHistory.empty());a.setMenu(Application::MenuState::Pause);a.activate(9);CHECK(a.enterWorld(first));CHECK(a.m_player.position==glm::vec3(100,30,100)&&a.m_dayNight.isNight()&&a.m_inventory.hotbarSlot(0).count==8);CHECK(a.m_world.captureFurnaces().size()==1);
  a.m_dayNight.skipToMorning();a.m_player.position={500.5f,9,501};a.m_player.yaw=-90;a.m_player.pitch=-15;for(int x=30;x<=32;++x)for(int z=30;z<=32;++z)a.m_world.loadChunk(x,z);a.m_world.setTaskBudgets(0,100,100);a.m_world.updateLighting();a.m_world.update(a.m_player.position);for(int pov=0;pov<3;++pov){for(int scale:{1,2})snapshot(a,output,"camera"+std::to_string(pov),scale);a.m_camera.cyclePOV();}
  a.setMenu(Application::MenuState::Pause);a.activate(9);a.activate(1);for(int scale:{1,2})snapshot(a,output,"worlds",scale);a.activate(6);CHECK(a.m_menuController.focus==0);for(int scale:{1,2})snapshot(a,output,"delete",scale);a.activate(0);CHECK(a.m_repository.list().size()==2);a.activate(6);a.activate(11);CHECK(a.m_repository.list().size()==1);
 }
};
int main(int argc,char** argv){if(!glfwInit())return 77;glfwWindowHint(GLFW_VISIBLE,GLFW_FALSE);auto* probe=glfwCreateWindow(64,64,"Probe",nullptr,nullptr);if(!probe){glfwTerminate();return 77;}glfwDestroyWindow(probe);glfwTerminate();auto root=std::filesystem::temp_directory_path()/"minecraft-menus-application-tests";std::filesystem::create_directories(root);
#ifdef _WIN32
 _putenv_s("APPDATA",root.string().c_str());
#else
 setenv("HOME",root.string().c_str(),1);
#endif
 int result=0;try{MenusApplicationTests::exercise(argc>1?std::filesystem::path(argv[1]):std::filesystem::path{});}catch(const std::exception& e){std::cerr<<e.what()<<'\n';result=1;}std::filesystem::remove_all(root);return result;}
