#include "Application.h"
#include "GameState.h"
#include "SaveLoad.h"
#include "../utils/Raycaster.h"
#include "../player/InventoryLayout.h"
#include "../world/BlockRegistry.h"
#include <glad/gl.h>
#include <glm/gtc/matrix_transform.hpp>
#include <algorithm>
#include <iomanip>
#include <sstream>
#include <stdexcept>

Application::Application(){
  if(!glfwInit())throw std::runtime_error("Could not initialize GLFW");
  glfwWindowHint(GLFW_CONTEXT_VERSION_MAJOR,3);glfwWindowHint(GLFW_CONTEXT_VERSION_MINOR,3);glfwWindowHint(GLFW_OPENGL_PROFILE,GLFW_OPENGL_CORE_PROFILE);
  m_window=glfwCreateWindow(1280,720,"Minecraft Superflat",nullptr,nullptr);if(!m_window){glfwTerminate();throw std::runtime_error("Could not create window");}
  glfwMakeContextCurrent(m_window);if(!gladLoadGL(reinterpret_cast<GLADloadfunc>(glfwGetProcAddress)))throw std::runtime_error("Could not load OpenGL");
  m_renderer=std::make_unique<Renderer>();glfwSetWindowUserPointer(m_window,this);glfwSetCursorPosCallback(m_window,cursor);glfwSetScrollCallback(m_window,scroll);glfwSetMouseButtonCallback(m_window,mouseButton);glfwSetKeyCallback(m_window,key);
  glfwSetInputMode(m_window,GLFW_CURSOR,GLFW_CURSOR_DISABLED);glfwSwapInterval(1);glEnable(GL_DEPTH_TEST);glEnable(GL_CULL_FACE);glCullFace(GL_BACK);loadGameState();
}
Application::~Application(){saveGameState();m_renderer.reset();if(m_window)glfwDestroyWindow(m_window);glfwTerminate();}
void Application::saveGameState()const{SaveLoad::save(GameState::capture(m_inventory,m_world));}
void Application::loadGameState(){SaveData data;if(SaveLoad::load(data))GameState::apply(data,m_inventory,m_world);}
void Application::setInventoryOpen(bool open,bool table){m_inventoryOpen=open;m_tableOpen=open&&table;m_captured=!open;m_firstMouse=true;glfwSetInputMode(m_window,GLFW_CURSOR,m_captured?GLFW_CURSOR_DISABLED:GLFW_CURSOR_NORMAL);}
void Application::cursor(GLFWwindow*w,double x,double y){auto*a=static_cast<Application*>(glfwGetWindowUserPointer(w));if(!a->m_captured)return;if(a->m_firstMouse){a->m_lastX=x;a->m_lastY=y;a->m_firstMouse=false;}a->m_player.look(static_cast<float>(x-a->m_lastX),static_cast<float>(a->m_lastY-y));a->m_lastX=x;a->m_lastY=y;}
void Application::scroll(GLFWwindow*w,double,double y){auto*a=static_cast<Application*>(glfwGetWindowUserPointer(w));if(a->m_inventoryOpen){const int pages=static_cast<int>((allPlaceableBlocks().size()+InventoryLayout::CREATIVE_PAGE_SIZE-1)/InventoryLayout::CREATIVE_PAGE_SIZE);a->m_creativePage=std::clamp(a->m_creativePage+(y<0?1:-1),0,std::max(0,pages-1));return;}a->m_camera.fov=std::clamp(a->m_camera.fov-static_cast<float>(y)*2.f,30.f,90.f);}
void Application::key(GLFWwindow*w,int k,int,int action,int){auto*a=static_cast<Application*>(glfwGetWindowUserPointer(w));if(action!=GLFW_PRESS)return;if(k>=GLFW_KEY_1&&k<=GLFW_KEY_9)a->m_inventory.select(k-GLFW_KEY_1);else if(k==GLFW_KEY_E)a->setInventoryOpen(!a->m_inventoryOpen);else if(k==GLFW_KEY_ESCAPE){if(a->m_inventoryOpen)a->setInventoryOpen(false);else{a->m_captured=!a->m_captured;a->m_firstMouse=true;glfwSetInputMode(w,GLFW_CURSOR,a->m_captured?GLFW_CURSOR_DISABLED:GLFW_CURSOR_NORMAL);}}else if(k==GLFW_KEY_F)a->m_player.toggleFly();else if(k==GLFW_KEY_G){a->m_fullAutoBreakEnabled=!a->m_fullAutoBreakEnabled;a->m_semiAutoMiningActive=false;a->m_player.resetMiningProgress();}else if(k==GLFW_KEY_F5)a->m_camera.togglePOV();}
void Application::mouseButton(GLFWwindow*w,int button,int action,int){auto*a=static_cast<Application*>(glfwGetWindowUserPointer(w));if(action!=GLFW_PRESS)return;if(a->m_inventoryOpen){if(button!=GLFW_MOUSE_BUTTON_LEFT)return;double cursorX,cursorY;int windowWidth,windowHeight,frameWidth,frameHeight;glfwGetCursorPos(w,&cursorX,&cursorY);glfwGetWindowSize(w,&windowWidth,&windowHeight);glfwGetFramebufferSize(w,&frameWidth,&frameHeight);if(windowWidth<=0||windowHeight<=0)return;auto hit=InventoryLayout::hitTest(static_cast<float>(cursorX*frameWidth/windowWidth),static_cast<float>(cursorY*frameHeight/windowHeight),frameWidth,frameHeight,a->m_tableOpen);if(hit.area==InventoryLayout::Area::HOTBAR)a->m_inventory.swapHotbar(hit.index);else if(hit.area==InventoryLayout::Area::BACKPACK)a->m_inventory.swapBackpack(hit.index);else if(hit.area==InventoryLayout::Area::PERSONAL_CRAFT)a->m_inventory.swapCraft(false,hit.index);else if(hit.area==InventoryLayout::Area::TABLE_CRAFT)a->m_inventory.swapCraft(true,hit.index);else if(hit.area==InventoryLayout::Area::CRAFT_OUTPUT)a->m_inventory.craftOutput(a->m_tableOpen);else if(hit.area==InventoryLayout::Area::CREATIVE){const int blockIndex=1+a->m_creativePage*InventoryLayout::CREATIVE_PAGE_SIZE+hit.index;if(blockIndex<static_cast<int>(BLOCK_TYPE_COUNT))a->m_inventory.giveCreative(static_cast<BlockType>(blockIndex));}return;}if(button!=GLFW_MOUSE_BUTTON_RIGHT||!a->m_captured||a->m_clickCooldown>0)return;glm::vec3 origin=a->m_camera.position(a->m_player,a->m_world),direction=a->m_camera.direction(a->m_player,origin);auto hit=Raycaster::cast(a->m_world,origin,direction,a->m_camera.thirdPerson?12.f:6.f);if(!hit.hit)return;if(a->m_world.getBlock(hit.block.x,hit.block.y,hit.block.z)==BlockType::CRAFTING_TABLE){a->setInventoryOpen(true,true);return;}if(a->m_player.overlapsBlock(hit.adjacent))return;BlockType type=a->m_inventory.selectedType();if(type!=BlockType::AIR&&a->m_inventory.consumeSelected())a->m_world.setBlock(hit.adjacent.x,hit.adjacent.y,hit.adjacent.z,type);a->m_clickCooldown=.12f;}
void Application::input(float){if(m_inventoryOpen){m_player.velocity.x=0;m_player.velocity.z=0;if(m_player.isFlying)m_player.velocity.y=0;return;}glm::vec3 forward=m_player.forward();forward.y=0;if(glm::length(forward)>0)forward=glm::normalize(forward);glm::vec3 right=glm::normalize(glm::cross(forward,glm::vec3{0,1,0}));glm::vec3 move{0};
  if(glfwGetKey(m_window,GLFW_KEY_W)==GLFW_PRESS)move+=forward;
  if(glfwGetKey(m_window,GLFW_KEY_S)==GLFW_PRESS)move-=forward;
  if(glfwGetKey(m_window,GLFW_KEY_D)==GLFW_PRESS)move+=right;
  if(glfwGetKey(m_window,GLFW_KEY_A)==GLFW_PRESS)move-=right;
  if(glm::length(move)>0)move=glm::normalize(move);
  float speed=glfwGetKey(m_window,GLFW_KEY_LEFT_CONTROL)==GLFW_PRESS?10.f:5.f;m_player.velocity.x=move.x*speed;m_player.velocity.z=move.z*speed;
  if(m_player.isFlying){m_player.velocity.y=0;if(glfwGetKey(m_window,GLFW_KEY_SPACE)==GLFW_PRESS)m_player.velocity.y=speed;if(glfwGetKey(m_window,GLFW_KEY_LEFT_SHIFT)==GLFW_PRESS)m_player.velocity.y=-speed;}else if(glfwGetKey(m_window,GLFW_KEY_SPACE)==GLFW_PRESS)m_player.jump();
}
void Application::updateMining(float dt){const bool leftDown=glfwGetMouseButton(m_window,GLFW_MOUSE_BUTTON_LEFT)==GLFW_PRESS;const bool justPressed=leftDown&&!m_leftMouseWasDown;m_leftMouseWasDown=leftDown;if(justPressed)m_semiAutoMiningActive=true;if(!leftDown){m_semiAutoMiningActive=false;m_player.resetMiningProgress();return;}if(m_inventoryOpen||!m_captured||m_player.targetedBlock.y<=0||(!m_fullAutoBreakEnabled&&!m_semiAutoMiningActive)){m_player.resetMiningProgress();return;}BlockType type=m_world.getBlock(m_player.targetedBlock.x,m_player.targetedBlock.y,m_player.targetedBlock.z);if(type==BlockType::AIR){m_player.clearMiningTarget();return;}const ItemStack held=m_inventory.selectedStack();const auto& properties=getBlockProperties(type);if(m_player.advanceMining(type,dt,held)){const glm::ivec3 brokenBlock=m_player.targetedBlock;if(m_world.setBlock(brokenBlock.x,brokenBlock.y,brokenBlock.z,BlockType::AIR)){m_renderer->spawnBlockBreak(brokenBlock,type);if(canDropBlock(held,properties))m_inventory.add(miningDrop(type));if(toolMatches(held,properties))m_inventory.damageSelectedTool();}m_semiAutoMiningActive=m_fullAutoBreakEnabled;m_player.clearMiningTarget();}}
void Application::run(){double last=glfwGetTime();while(!glfwWindowShouldClose(m_window)){double now=glfwGetTime();float dt=std::min(static_cast<float>(now-last),.05f);last=now;m_clickCooldown=std::max(0.f,m_clickCooldown-dt);glfwPollEvents();m_dayNight.update(dt);m_world.update(m_player.position);input(dt);m_player.update(dt,m_world);
    int width,height;glfwGetFramebufferSize(m_window,&width,&height);glViewport(0,0,width,height);glClear(GL_COLOR_BUFFER_BIT|GL_DEPTH_BUFFER_BIT);glm::mat4 projection=glm::perspective(glm::radians(m_camera.fov),width/static_cast<float>(std::max(height,1)),.1f,500.f);glm::vec3 cameraPos=m_camera.position(m_player,m_world),cameraDir=m_camera.direction(m_player,cameraPos);RayHit target=Raycaster::cast(m_world,cameraPos,cameraDir,m_camera.thirdPerson?12.f:6.f);
    if(target.hit&&target.block.y>0)m_player.setMiningTarget(target.block);else m_player.clearMiningTarget();updateMining(dt);
    BlockType selected=target.hit?m_world.getBlock(target.block.x,target.block.y,target.block.z):BlockType::AIR;const char* name=selected==BlockType::AIR?"NONE":blockName(selected);
    std::ostringstream hud;hud<<std::fixed<<std::setprecision(1)<<"POS: "<<m_player.position.x<<" "<<m_player.position.y<<" "<<m_player.position.z<<"\nFLY: "<<(m_player.isFlying?"ON":"OFF")<<"\nBREAK: "<<(m_fullAutoBreakEnabled?"FULL AUTO":"SEMI AUTO")<<"\nTARGET: "<<name<<"\nTIME: "<<static_cast<int>(m_dayNight.time()*24.f)<<":00";
    m_renderer->draw(m_world,m_player,m_camera.thirdPerson,dt,m_camera.view(m_player,cameraPos),projection,cameraPos,target,width,height,hud.str(),m_inventory,m_inventoryOpen,m_tableOpen,m_creativePage,m_dayNight);glfwSwapBuffers(m_window);}}
