#include "Application.h"
#include "GameState.h"
#include "SaveLoad.h"
#include "../utils/Raycaster.h"
#include "../player/InventoryLayout.h"
#include "../player/CreativeCatalog.h"
#include "../player/Respawn.h"
#include "../world/BlockRegistry.h"
#include <glad/gl.h>
#include <glm/gtc/matrix_transform.hpp>
#include <algorithm>
#include <iomanip>
#include <sstream>
#include <stdexcept>

Application::Application(){
  if(!glfwInit())throw std::runtime_error("Could not initialize GLFW");
  glfwWindowHint(GLFW_CONTEXT_VERSION_MAJOR,3);glfwWindowHint(GLFW_CONTEXT_VERSION_MINOR,3);glfwWindowHint(GLFW_OPENGL_PROFILE,GLFW_OPENGL_CORE_PROFILE);
  m_window=glfwCreateWindow(1280,720,"Minecraft Superflat",nullptr,nullptr);if(!m_window){glfwTerminate();throw std::runtime_error("Could not create window");}
  glfwMakeContextCurrent(m_window);if(!gladLoadGL(reinterpret_cast<GLADloadfunc>(glfwGetProcAddress)))throw std::runtime_error("Could not load OpenGL");
  m_renderer=std::make_unique<Renderer>();glfwSetWindowUserPointer(m_window,this);glfwSetCursorPosCallback(m_window,cursor);glfwSetScrollCallback(m_window,scroll);glfwSetMouseButtonCallback(m_window,mouseButton);glfwSetKeyCallback(m_window,key);
  glfwSetInputMode(m_window,GLFW_CURSOR,GLFW_CURSOR_DISABLED);glfwSwapInterval(1);glEnable(GL_DEPTH_TEST);glEnable(GL_CULL_FACE);glCullFace(GL_BACK);loadGameState();
}
Application::~Application(){saveGameState();m_renderer.reset();if(m_window)glfwDestroyWindow(m_window);glfwTerminate();}
void Application::saveGameState()const{SaveLoad::save(GameState::capture(m_inventory,m_world,m_player,m_mobs));}
void Application::loadGameState(){SaveData data;if(SaveLoad::load(data))GameState::apply(data,m_inventory,m_world,m_player,m_mobs);}
void Application::setInventoryOpen(bool open,bool table){m_inventoryOpen=open;m_tableOpen=open&&table;m_captured=!open;m_firstMouse=true;if(open){m_sprint.cancel();m_eating.cancel();}glfwSetInputMode(m_window,GLFW_CURSOR,m_captured?GLFW_CURSOR_DISABLED:GLFW_CURSOR_NORMAL);}
void Application::cursor(GLFWwindow*w,double x,double y){auto*a=static_cast<Application*>(glfwGetWindowUserPointer(w));if(!a->m_captured)return;if(a->m_firstMouse){a->m_lastX=x;a->m_lastY=y;a->m_firstMouse=false;}a->m_player.look(static_cast<float>(x-a->m_lastX),static_cast<float>(a->m_lastY-y));a->m_lastX=x;a->m_lastY=y;}
void Application::scroll(GLFWwindow*w,double,double y){auto*a=static_cast<Application*>(glfwGetWindowUserPointer(w));if(a->m_inventoryOpen){const int pages=static_cast<int>((creativeCatalog().size()+InventoryLayout::CREATIVE_PAGE_SIZE-1)/InventoryLayout::CREATIVE_PAGE_SIZE);a->m_creativePage=std::clamp(a->m_creativePage+(y<0?1:-1),0,std::max(0,pages-1));return;}a->m_camera.adjustFov(-static_cast<float>(y)*2.f);}
void Application::key(GLFWwindow*w,int k,int,int action,int){auto*a=static_cast<Application*>(glfwGetWindowUserPointer(w));if(action!=GLFW_PRESS)return;if(k>=GLFW_KEY_1&&k<=GLFW_KEY_9){a->m_inventory.select(k-GLFW_KEY_1);a->m_eating.cancel();}else if(k==GLFW_KEY_E)a->setInventoryOpen(!a->m_inventoryOpen);else if(k==GLFW_KEY_ESCAPE){if(a->m_inventoryOpen)a->setInventoryOpen(false);else{a->m_captured=!a->m_captured;a->m_firstMouse=true;if(!a->m_captured)a->m_eating.cancel();glfwSetInputMode(w,GLFW_CURSOR,a->m_captured?GLFW_CURSOR_DISABLED:GLFW_CURSOR_NORMAL);}}else if(k==GLFW_KEY_F){a->m_player.toggleFly();if(a->m_player.isFlying){a->m_sprint.cancel();a->m_eating.cancel();}}else if(k==GLFW_KEY_LEFT_SHIFT&&!a->m_inventoryOpen&&!a->m_player.isFlying&&a->m_player.onGround){a->m_eating.cancel();a->m_sprint.toggle();}else if(k==GLFW_KEY_W&&!a->m_inventoryOpen&&!a->m_player.isFlying&&a->m_player.onGround){if(a->m_sprint.forwardPressed(glfwGetTime()))a->m_eating.cancel();}else if(k==GLFW_KEY_G){a->m_breakMode.toggle();a->m_semiAutoMiningActive=false;a->m_player.resetMiningProgress();a->m_player.resetMiningCooldown();}else if(k==GLFW_KEY_F5)a->m_camera.togglePOV();}
void Application::mouseButton(GLFWwindow*w,int button,int action,int){auto*a=static_cast<Application*>(glfwGetWindowUserPointer(w));if(action!=GLFW_PRESS)return;if(a->m_inventoryOpen){if(button!=GLFW_MOUSE_BUTTON_LEFT)return;double cursorX,cursorY;int windowWidth,windowHeight,frameWidth,frameHeight;glfwGetCursorPos(w,&cursorX,&cursorY);glfwGetWindowSize(w,&windowWidth,&windowHeight);glfwGetFramebufferSize(w,&frameWidth,&frameHeight);if(windowWidth<=0||windowHeight<=0)return;auto hit=InventoryLayout::hitTest(static_cast<float>(cursorX*frameWidth/windowWidth),static_cast<float>(cursorY*frameHeight/windowHeight),frameWidth,frameHeight,a->m_tableOpen);if(hit.area==InventoryLayout::Area::HOTBAR)a->m_inventory.swapHotbar(hit.index);else if(hit.area==InventoryLayout::Area::BACKPACK)a->m_inventory.swapBackpack(hit.index);else if(hit.area==InventoryLayout::Area::PERSONAL_CRAFT)a->m_inventory.swapCraft(false,hit.index);else if(hit.area==InventoryLayout::Area::TABLE_CRAFT)a->m_inventory.swapCraft(true,hit.index);else if(hit.area==InventoryLayout::Area::CRAFT_OUTPUT)a->m_inventory.craftOutput(a->m_tableOpen);else if(hit.area==InventoryLayout::Area::CREATIVE){const int itemIndex=a->m_creativePage*InventoryLayout::CREATIVE_PAGE_SIZE+hit.index;if(itemIndex<static_cast<int>(creativeCatalog().size()))a->m_inventory.giveCreative(creativeCatalog()[static_cast<std::size_t>(itemIndex)]);}return;}if(button!=GLFW_MOUSE_BUTTON_RIGHT||!a->m_captured)return;const ItemStack selected=a->m_inventory.selectedStack();if(selected.kind==ItemKind::FOOD&&!selected.empty()){if(a->m_player.survival.canEat()){a->m_eating.start(a->m_inventory.selectedSlot(),selected.foodType);a->m_sprint.cancel();}return;}if(a->m_clickCooldown>0)return;glm::vec3 origin=a->m_camera.position(a->m_player,a->m_world),direction=a->m_camera.direction(a->m_player,origin);auto hit=Raycaster::cast(a->m_world,origin,direction,a->m_camera.thirdPerson?12.f:6.f);if(!hit.hit)return;if(a->m_world.getBlock(hit.block.x,hit.block.y,hit.block.z)==BlockType::CRAFTING_TABLE){a->setInventoryOpen(true,true);return;}if(a->m_player.overlapsBlock(hit.adjacent))return;BlockType type=a->m_inventory.selectedType();if(type!=BlockType::AIR&&a->m_inventory.consumeSelected())a->m_world.setBlock(hit.adjacent.x,hit.adjacent.y,hit.adjacent.z,type);a->m_clickCooldown=.12f;}
void Application::input(float){if(m_inventoryOpen){m_player.velocity.x=0;m_player.velocity.z=0;if(m_player.isFlying)m_player.velocity.y=0;m_sprint.cancel();return;}glm::vec3 forward=m_player.forward();forward.y=0;if(glm::length(forward)>0)forward=glm::normalize(forward);glm::vec3 right=glm::normalize(glm::cross(forward,glm::vec3{0,1,0}));glm::vec3 move{0};
  if(glfwGetKey(m_window,GLFW_KEY_W)==GLFW_PRESS)move+=forward;
  if(glfwGetKey(m_window,GLFW_KEY_S)==GLFW_PRESS)move-=forward;
  if(glfwGetKey(m_window,GLFW_KEY_D)==GLFW_PRESS)move+=right;
  if(glfwGetKey(m_window,GLFW_KEY_A)==GLFW_PRESS)move-=right;
  if(glm::length(move)>0)move=glm::normalize(move);
  if(!m_player.survival.canSprint())m_sprint.cancel();
  const bool forwardIntent=glm::length(move)>0&&glm::dot(move,forward)>.1f;m_sprint.evaluate(forwardIntent,!m_player.isFlying&&!m_eating.active()&&m_player.survival.canSprint());const float speed=m_sprint.movementSpeed();m_player.velocity.x=move.x*speed;m_player.velocity.z=move.z*speed;
  if(m_player.isFlying){m_player.velocity.y=0;if(glfwGetKey(m_window,GLFW_KEY_SPACE)==GLFW_PRESS)m_player.velocity.y=speed;if(glfwGetKey(m_window,GLFW_KEY_LEFT_CONTROL)==GLFW_PRESS)m_player.velocity.y=-speed;}else if(glfwGetKey(m_window,GLFW_KEY_SPACE)==GLFW_PRESS&&m_player.jump(m_sprint.active()))m_eating.cancel();
}
void Application::updateEating(float dt){if(!m_eating.active())return;EatingContext context;context.rightHeld=glfwGetMouseButton(m_window,GLFW_MOUSE_BUTTON_RIGHT)==GLFW_PRESS;context.captured=m_captured;context.inventoryOpen=m_inventoryOpen;context.onGround=m_player.onGround;context.flying=m_player.isFlying;context.sprinting=m_sprint.active();context.canEat=m_player.survival.canEat();context.horizontalSpeed=glm::length(glm::vec2{m_player.velocity.x,m_player.velocity.z});context.selectedSlot=m_inventory.selectedSlot();context.selected=m_inventory.selectedStack();const FoodType food=m_eating.food();if(m_eating.update(dt,m_eating.canContinue(context))&&m_inventory.consumeSelectedFood(food))m_player.survival.eat(food);}
void Application::respawnPlayer(){m_sprint.cancel();m_eating.cancel();m_inventory.clear();m_world.loadChunk(31,31);m_player.respawn(safeRespawnPosition(m_world));}
void Application::updateMining(float dt,const glm::vec3& origin,const glm::vec3& direction,const RayHit& blockHit){const bool leftDown=glfwGetMouseButton(m_window,GLFW_MOUSE_BUTTON_LEFT)==GLFW_PRESS;const bool justPressed=leftDown&&!m_leftMouseWasDown;m_leftMouseWasDown=leftDown;if(!leftDown){m_primaryAttackConsumed=false;m_semiAutoMiningActive=false;m_player.resetMiningProgress();m_player.resetMiningCooldown();return;}if(justPressed&&!m_inventoryOpen&&m_captured){const MobHit mobHit=m_mobs.raycast(origin,direction);if(mobHit.hit&&(!blockHit.hit||mobHit.distance<blockHit.distance)){m_primaryAttackConsumed=true;m_semiAutoMiningActive=false;m_player.resetMiningProgress();if(m_attackCooldown<=0){const ItemStack held=m_inventory.selectedStack();const bool damaged=m_mobs.damage(mobHit.id,PassiveMobSystem::attackDamage(held),m_player.position,m_loot,[this](const glm::vec3& position,const ItemStack& stack){m_renderer->spawnDrop(position,stack);});if(damaged){if(held.kind==ItemKind::TOOL)m_inventory.damageSelectedTool();m_attackCooldown=.35f;m_eating.cancel();}}return;}}if(m_primaryAttackConsumed){m_player.resetMiningProgress();return;}if(justPressed)m_semiAutoMiningActive=true;if(m_inventoryOpen||!m_captured||m_player.targetedBlock.y<=0||(!m_breakMode.fullAutoEnabled()&&!m_semiAutoMiningActive)){m_player.resetMiningProgress();return;}BlockType type=m_world.getBlock(m_player.targetedBlock.x,m_player.targetedBlock.y,m_player.targetedBlock.z);if(type==BlockType::AIR){m_player.clearMiningTarget();return;}const ItemStack held=m_inventory.selectedStack();const auto& properties=getBlockProperties(type);if(m_player.advanceMining(type,dt,held)){const glm::ivec3 brokenBlock=m_player.targetedBlock;if(m_world.setBlock(brokenBlock.x,brokenBlock.y,brokenBlock.z,BlockType::AIR)){m_renderer->spawnBlockBreak(brokenBlock,type);if(canDropBlock(type,held))m_renderer->spawnDrop(glm::vec3(brokenBlock),ItemStack::block(miningDrop(type)));if(m_loot.dropsApple(type))m_renderer->spawnDrop(glm::vec3(brokenBlock),ItemStack::food(FoodType::APPLE));if(toolMatches(held,properties))m_inventory.damageSelectedTool();if(m_breakMode.fullAutoEnabled())m_player.startMiningCooldown();}m_semiAutoMiningActive=m_breakMode.fullAutoEnabled();m_player.clearMiningTarget();}}
void Application::run(){double last=glfwGetTime();while(!glfwWindowShouldClose(m_window)){double now=glfwGetTime();float dt=std::min(static_cast<float>(now-last),.05f);last=now;m_clickCooldown=std::max(0.f,m_clickCooldown-dt);m_attackCooldown=std::max(0.f,m_attackCooldown-dt);glfwPollEvents();m_dayNight.update(dt);m_world.update(m_player.position);input(dt);const glm::vec3 previousPosition=m_player.position;const int previousHealth=m_player.survival.health();m_player.update(dt,m_world);if(m_sprint.active())m_player.survival.addSprintDisplacement(m_player.position.x-previousPosition.x,m_player.position.z-previousPosition.z);m_player.survival.update(dt);if(m_player.survival.health()<previousHealth)m_eating.cancel();else updateEating(dt);if(m_player.survival.dead())respawnPlayer();m_mobs.update(dt,m_world,m_player.position,m_dayNight.daylight());m_renderer->updateDrops(dt,m_world,m_player.position,[this](const ItemStack& stack){return m_inventory.add(stack);});m_camera.updateFov(dt,m_sprint.active());
    int width,height;glfwGetFramebufferSize(m_window,&width,&height);glViewport(0,0,width,height);glClear(GL_COLOR_BUFFER_BIT|GL_DEPTH_BUFFER_BIT);glm::mat4 projection=glm::perspective(glm::radians(m_camera.fov),width/static_cast<float>(std::max(height,1)),.1f,500.f);glm::vec3 cameraPos=m_camera.position(m_player,m_world),cameraDir=m_camera.direction(m_player,cameraPos);RayHit target=Raycaster::cast(m_world,cameraPos,cameraDir,m_camera.thirdPerson?12.f:6.f);
    if(target.hit&&target.block.y>0)m_player.setMiningTarget(target.block);else m_player.clearMiningTarget();updateMining(dt,cameraPos,cameraDir,target);
    double cursorX=0,cursorY=0;int windowWidth=0,windowHeight=0;glfwGetCursorPos(m_window,&cursorX,&cursorY);glfwGetWindowSize(m_window,&windowWidth,&windowHeight);const float mouseX=windowWidth>0?static_cast<float>(cursorX*width/windowWidth):0.f,mouseY=windowHeight>0?static_cast<float>(cursorY*height/windowHeight):0.f;
    BlockType selected=target.hit?m_world.getBlock(target.block.x,target.block.y,target.block.z):BlockType::AIR;const char* name=selected==BlockType::AIR?"NONE":blockName(selected);
    std::ostringstream hud;hud<<std::fixed<<std::setprecision(1)<<"POS: "<<m_player.position.x<<" "<<m_player.position.y<<" "<<m_player.position.z<<"\nFLY: "<<(m_player.isFlying?"ON":"OFF")<<"\nSPRINT: "<<m_sprint.hudText()<<"\nBREAK: "<<m_breakMode.getCurrentBreakModeText()<<"\nTARGET: "<<name<<"\nTIME: "<<static_cast<int>(m_dayNight.time()*24.f)<<":00";
    m_renderer->draw(m_world,m_player,m_mobs,m_camera.thirdPerson,dt,m_camera.view(m_player,cameraPos),projection,cameraPos,target,width,height,hud.str(),m_inventory,m_inventoryOpen,m_tableOpen,m_creativePage,mouseX,mouseY,m_dayNight);glfwSwapBuffers(m_window);}}
