#include "Application.h"
#include "GameState.h"
#include "../player/PlayerPhysics.h"
#include "../player/Respawn.h"
#include "../player/InventoryLayout.h"
#include "../utils/Raycaster.h"
#include <charconv>
#include <cmath>
#include <ctime>
#include <iomanip>
#include <random>
#include <sstream>

namespace {const char* modeName(GameMode mode){return mode==GameMode::Creative?"Creative":"Survival";}}
MenuView Application::menuView()const{
  MenuView v;v.notice=m_notice;
  auto button=[&](int id,std::string label,float y,bool enabled=true,float value=-1){v.widgets.push_back({id,std::move(label),240,y,800,44,enabled,value});};
  switch(m_menu){
    case MenuState::Title:v.title="Minecraft Superflat";button(1,"Singleplayer",200);button(2,"Settings",264);button(3,"Quit",328);break;
    case MenuState::Worlds:{v.title="Singleplayer worlds";int start=m_menuController.scroll;for(int i=start;i<std::min(start+8,static_cast<int>(m_worlds.size()));++i){const auto& w=m_worlds[i];std::time_t time=static_cast<std::time_t>(w.lastPlayed);std::ostringstream date;auto* t=std::localtime(&time);if(t)date<<std::put_time(t,"%Y-%m-%d %H:%M");std::string label=(i==m_selectedWorld?"> ":"")+w.name+"  |  "+std::to_string(w.seed)+"  "+modeName(w.mode)+"  "+date.str();if(!w.error.empty())label=w.name+": "+w.error;v.widgets.push_back({1000+i,label,160,130.f+(i-start)*48,960,38});}
      const bool selected=m_selectedWorld>=0&&m_selectedWorld<static_cast<int>(m_worlds.size());v.widgets.push_back({4,"Play",160,540,220,44,selected&&m_worlds[m_selectedWorld].error.empty()});v.widgets.push_back({5,"New World",400,540,220,44});v.widgets.push_back({6,"Delete",640,540,220,44,selected});v.widgets.push_back({0,"Back",880,540,220,44});break;}
    case MenuState::Create:v.title="New world";button(20,"Name: "+(m_textTarget==20?m_worldName.display():m_worldName.text),170);button(21,"Seed (blank = random): "+(m_textTarget==21?m_seedText.display():m_seedText.text),234);button(22,std::string("Mode: ")+modeName(m_newMode),298);button(23,"Create and Play",390);button(0,"Cancel",454);break;
    case MenuState::Pause:v.title="Paused";button(7,"Resume",180);button(2,"Settings",244);button(8,"Keybinds",308);button(9,"Save & Quit",372);break;
    case MenuState::Settings:v.title="Settings";button(30,std::string(m_sessionActive?"Game Mode: ":"Default New World Mode: ")+modeName(m_sessionActive?m_player.gameMode():m_settings.defaultMode),124);button(31,"View distance: "+std::to_string(m_settings.viewDistance)+" chunks",180,true,(m_settings.viewDistance-2)/6.f);button(32,"Base FOV: "+std::to_string(static_cast<int>(m_settings.baseFov)),236,true,(m_settings.baseFov-30)/60);{std::ostringstream n;n<<std::fixed<<std::setprecision(2)<<m_settings.mouseSensitivity;button(33,"Mouse sensitivity: "+n.str(),292,true,(m_settings.mouseSensitivity-.01f)/.99f);}button(34,std::string("VSync: ")+(m_settings.vsync?"On":"Off"),348);button(35,std::string("Invert Y: ")+(m_settings.invertY?"On":"Off"),404);button(36,std::string("Raw mouse: ")+(glfwRawMouseMotionSupported()?(m_settings.rawMouseInput?"On":"Off"):"Unavailable"),460,glfwRawMouseMotionSupported());v.widgets.push_back({8,"Keybinds",240,532,380,44});v.widgets.push_back({0,"Done",660,532,380,44});break;
    case MenuState::Keybinds:{v.title=m_keybindCapture>=0?"Press a key or mouse button - Escape cancels":"Keybindings";int start=m_menuController.scroll;for(int i=start;i<std::min(start+8,static_cast<int>(SettingsState::ACTION_COUNT));++i){auto a=static_cast<KeyAction>(i);std::string label=std::string(SettingsState::actionLabel(a))+": "+SettingsState::bindingName(m_settings.key(a));if(m_keybindCapture==i)label+=" ...";v.widgets.push_back({100+i,label,200,132.f+(i-start)*48,680,38});v.widgets.push_back({200+i,"Reset",900,132.f+(i-start)*48,180,38});}v.widgets.push_back({10,"Reset All",240,540,380,44});v.widgets.push_back({0,"Done",660,540,380,44});break;}
    case MenuState::Delete:v.title="Delete world?";v.notice="Delete "+(m_selectedWorld>=0?m_worlds[m_selectedWorld].name:"")+"? This cannot be undone.";button(0,"Cancel",280);button(11,"Delete this world",344);break;
    case MenuState::Swap:v.title="Swap conflicting bindings?";button(0,"Cancel",280);button(12,"Swap",344);break;
    case MenuState::Gameplay:break;
  }
  if(m_menu==MenuState::Keybinds||m_menu==MenuState::Worlds){int count=m_menu==MenuState::Worlds?static_cast<int>(m_worlds.size()):static_cast<int>(SettingsState::ACTION_COUNT);if(count>8){v.widgets.push_back({80,"<",1126,132,28,38,m_menuController.scroll>0});v.widgets.push_back({81,">",1126,468,28,38,m_menuController.scroll+8<count});v.title+="  "+std::to_string(m_menuController.scroll+1)+"-"+std::to_string(std::min(count,m_menuController.scroll+8))+" / "+std::to_string(count);}}
  return v;
}
void Application::refreshWorlds(){m_worlds=m_repository.list();m_selectedWorld=m_worlds.empty()?-1:0;}
void Application::unloadWorld(){m_sessionActive=false;m_world.reset();m_inventory=Inventory{};m_player=Player{};m_mobs=PassiveMobSystem{};m_dayNight=DayNightCycle{};m_camera=PlayerCamera{};m_renderer=std::make_unique<Renderer>();m_inventoryOpen=m_tableOpen=m_furnaceOpen=m_chatOpen=false;m_creativePage=0;m_inventoryDragging=false;m_furnaceDragSource=-1;m_sprint.cancel();m_eating.cancel();m_messages.clear();m_commandHistory.clear();m_chatEntry={};m_historyIndex=m_chatScroll=0;m_input.suppress();m_clickCooldown=m_attackCooldown=m_useSwingTimer=0;m_primaryAttackConsumed=m_leftMouseWasDown=m_miningAnimation=false;m_hudVisible=true;}
bool Application::enterWorld(const WorldInfo& info){SaveData data;if(!info.error.empty()){m_notice=info.error;return false;}if(!m_repository.load(info.id,data,m_notice))return false;unloadWorld();m_activeWorld=info;GameState::apply(data,m_inventory,m_world,m_player,m_mobs);m_dayNight.setTime(data.timeOfDay);m_world.setViewDistance(m_settings.viewDistance);const auto p=m_player.position;if(p.x<Player::WIDTH*.5f||p.x>1000-Player::WIDTH*.5f||p.z<Player::WIDTH*.5f||p.z>1000-Player::WIDTH*.5f||p.y<1||p.y>254)m_player.position={500,8,500};for(int x=static_cast<int>(m_player.position.x-.3f)/16;x<=static_cast<int>(m_player.position.x+.3f)/16;++x)for(int z=static_cast<int>(m_player.position.z-.3f)/16;z<=static_cast<int>(m_player.position.z+.3f)/16;++z)m_world.loadChunk(x,z);
 if(PlayerPhysics::collides(m_player,m_player.position,m_world)){m_world.loadChunk(31,31);m_player.position=safeRespawnPosition(m_world,m_player.position);for(int y=7;y<=254&&PlayerPhysics::collides(m_player,m_player.position,m_world);++y)m_player.position={500.5f,static_cast<float>(y),500.5f};}
 m_camera.baseFov=m_camera.fov=m_settings.baseFov;m_sessionActive=true;m_notice="Seed: "+std::to_string(data.seed);setMenu(MenuState::Gameplay);return true;}
void Application::applySettings(){m_world.setViewDistance(m_settings.viewDistance);m_camera.baseFov=m_settings.baseFov;glfwSwapInterval(m_settings.vsync?1:0);if(glfwRawMouseMotionSupported())glfwSetInputMode(m_window,GLFW_RAW_MOUSE_MOTION,m_captured&&m_settings.rawMouseInput);}
void Application::back(){if(m_menu==MenuState::Title)return;if(m_menu==MenuState::Gameplay){if(m_inventoryOpen)setInventoryOpen(false);else if(m_chatOpen){m_chatOpen=false;syncCursor();}else setMenu(MenuState::Pause);}else if(m_menu==MenuState::Pause)setMenu(MenuState::Gameplay);else if(m_menu==MenuState::Settings)setMenu(m_settingsReturn);else if(m_menu==MenuState::Keybinds)setMenu(m_bindingsReturn);else if(m_menu==MenuState::Delete||m_menu==MenuState::Create)setMenu(MenuState::Worlds);else if(m_menu==MenuState::Swap)setMenu(MenuState::Keybinds);else setMenu(MenuState::Title);}
void Application::slider(int id,float value){value=std::clamp(value,0.f,1.f);if(id==31)m_settings.viewDistance=2+static_cast<int>(std::round(value*6));if(id==32)m_settings.baseFov=30+std::round(value*60);if(id==33)m_settings.mouseSensitivity=std::round((.01f+value*.99f)*100)/100;applySettings();if(!SettingsState::save(m_settings))m_notice="Could not save settings";}
void Application::bind(int action,int code){auto a=static_cast<KeyAction>(action);m_keybindCapture=-1;if(!SettingsState::validCode(code)||(code==GLFW_KEY_ESCAPE&&a!=KeyAction::Pause)){m_notice="Invalid binding; Escape is reserved for Pause";return;}auto conflicts=m_settings.conflicts(a,code);if(conflicts.empty()){if(m_settings.assign(a,code)){SettingsState::save(m_settings);m_notice="Binding saved";}return;}m_notice=std::string(SettingsState::actionLabel(a))+" conflicts with ";for(auto other:conflicts)m_notice+=std::string(SettingsState::actionLabel(other))+" ";if(conflicts.size()>1){m_notice+="- multiple conflicts; choose another input";return;}SettingsState candidate=m_settings;if(!candidate.assign(a,code,true)){m_notice+="- swap is invalid";return;}m_pendingAction=action;m_pendingCode=code;setMenu(MenuState::Swap);}
void Application::activate(int id){
 if(id>=1000){m_selectedWorld=id-1000;return;}if(id>=200&&id<200+static_cast<int>(SettingsState::ACTION_COUNT)){bind(id-200,SettingsState::defaultBinding(static_cast<KeyAction>(id-200)));return;}if(id>=100&&id<100+static_cast<int>(SettingsState::ACTION_COUNT)){m_keybindCapture=id-100;m_captureReady=m_input.allReleased();return;}
 switch(id){case 80:case 81:{int count=m_menu==MenuState::Worlds?static_cast<int>(m_worlds.size()):static_cast<int>(SettingsState::ACTION_COUNT);m_menuController.scroll=std::clamp(m_menuController.scroll+(id==80?-8:8),0,std::max(0,count-8));break;}case 0:back();break;case 1:refreshWorlds();setMenu(MenuState::Worlds);break;case 2:m_settingsReturn=m_menu;setMenu(MenuState::Settings);break;case 3:glfwSetWindowShouldClose(m_window,GLFW_TRUE);break;case 4:if(m_selectedWorld>=0)enterWorld(m_worlds[m_selectedWorld]);break;case 5:m_worldName={};m_seedText={};m_newMode=m_settings.defaultMode;setMenu(MenuState::Create);m_textTarget=20;break;case 6:setMenu(MenuState::Delete);break;case 7:setMenu(MenuState::Gameplay);break;case 8:m_bindingsReturn=m_menu;setMenu(MenuState::Keybinds);break;case 9:if(saveGameState()){unloadWorld();setMenu(MenuState::Title);}break;case 10:m_settings.resetBindings();SettingsState::save(m_settings);m_notice="Default bindings restored";break;case 11:if(m_selectedWorld>=0&&m_repository.remove(m_worlds[m_selectedWorld].id,m_notice)){refreshWorlds();setMenu(MenuState::Worlds);}break;case 12:if(m_settings.assign(static_cast<KeyAction>(m_pendingAction),m_pendingCode,true)){SettingsState::save(m_settings);m_notice="Bindings swapped";}setMenu(MenuState::Keybinds);break;case 20:case 21:m_textTarget=id;break;case 22:m_newMode=m_newMode==GameMode::Survival?GameMode::Creative:GameMode::Survival;break;
 case 23:{std::uint32_t seed=0;if(m_seedText.text.empty())seed=std::random_device{}();else{auto result=std::from_chars(m_seedText.text.data(),m_seedText.text.data()+m_seedText.text.size(),seed);if(result.ec!=std::errc{}||result.ptr!=m_seedText.text.data()+m_seedText.text.size()){m_notice="Seed must be an unsigned 32-bit decimal number";break;}}WorldInfo info;if(m_repository.create(m_worldName.text,seed,m_newMode,info,m_notice))enterWorld(info);break;}
 case 30:if(m_sessionActive)m_player.setGameMode(m_player.gameMode()==GameMode::Creative?GameMode::Survival:GameMode::Creative);else m_settings.defaultMode=m_settings.defaultMode==GameMode::Creative?GameMode::Survival:GameMode::Creative;break;case 34:m_settings.vsync=!m_settings.vsync;break;case 35:m_settings.invertY=!m_settings.invertY;break;case 36:m_settings.rawMouseInput=!m_settings.rawMouseInput;break;
 }if(id>=30&&id<=36){applySettings();if(!SettingsState::save(m_settings))m_notice="Could not save settings";}
}
void Application::handleMenuClick(double x,double y,int width,int height){if(width<=0||height<=0)return;auto view=menuView();int hit=m_menuController.hit(view,static_cast<float>(x*1280/width),static_cast<float>(y*720/height));if(hit>=0){m_menuController.focus=hit;activate(view.widgets[hit].id);}}
void Application::character(GLFWwindow*w,unsigned code){auto*a=static_cast<Application*>(glfwGetWindowUserPointer(w));if(a->m_keybindCapture>=0)return;if(a->m_chatOpen){if(a->m_chatReady)a->m_chatEntry.insert(code,256);}else if(a->m_menu==MenuState::Create){if(a->m_textTarget==20)a->m_worldName.insert(code,48);if(a->m_textTarget==21&&code>='0'&&code<='9')a->m_seedText.insert(code,10);}}
void Application::routeInput(int code,int action,int mods){
 m_input.event(code,action!=GLFW_RELEASE);
 if(m_keybindCapture>=0){if(code==GLFW_KEY_ESCAPE&&action==GLFW_PRESS){m_keybindCapture=-1;return;}if(!m_captureReady){m_captureReady=m_input.allReleased();return;}if(action==GLFW_PRESS)bind(m_keybindCapture,code);return;}
 if(m_chatOpen){if(action==GLFW_RELEASE){if(code==m_settings.key(KeyAction::OpenChat))m_chatReady=true;return;}if(code==GLFW_KEY_ESCAPE){m_chatOpen=false;syncCursor();return;}if(code==GLFW_KEY_ENTER){std::string entry=m_chatEntry.text;m_chatOpen=false;syncCursor();command(entry);m_chatEntry={};return;}if(code==GLFW_KEY_UP||code==GLFW_KEY_DOWN){m_historyIndex=std::clamp(m_historyIndex+(code==GLFW_KEY_UP?-1:1),0,static_cast<int>(m_commandHistory.size()));m_chatEntry.set(m_historyIndex<static_cast<int>(m_commandHistory.size())?m_commandHistory[m_historyIndex]:"");}else m_chatEntry.edit(code);return;}
 if(code==GLFW_KEY_ESCAPE&&action==GLFW_PRESS){back();return;}
 if(m_menu!=MenuState::Gameplay){
   auto view=menuView();if(code==1000){double x,y;int width,height;glfwGetCursorPos(m_window,&x,&y);glfwGetWindowSize(m_window,&width,&height);if(width<=0||height<=0)return;float px=static_cast<float>(x*1280/width),py=static_cast<float>(y*720/height);int hit=m_menuController.hit(view,px,py);if(action==GLFW_PRESS){m_menuController.pressed=hit;if(hit>=0){m_menuController.focus=hit;m_textTarget=0;auto& widget=view.widgets[hit];if(widget.value>=0)slider(widget.id,(px-widget.x)/widget.w);}}else if(action==GLFW_RELEASE){int pressed=m_menuController.pressed;m_menuController.pressed=-1;if(hit>=0&&hit==pressed)activate(view.widgets[hit].id);}return;}
   if(action==GLFW_RELEASE)return;
   if(m_menu==MenuState::Create&&m_textTarget&&(code==GLFW_KEY_LEFT||code==GLFW_KEY_RIGHT||code==GLFW_KEY_BACKSPACE||code==GLFW_KEY_DELETE||code==GLFW_KEY_HOME||code==GLFW_KEY_END)){(m_textTarget==20?m_worldName:m_seedText).edit(code);return;}
   if((code==GLFW_KEY_PAGE_UP||code==GLFW_KEY_PAGE_DOWN)&&(m_menu==MenuState::Keybinds||m_menu==MenuState::Worlds)){int count=m_menu==MenuState::Worlds?static_cast<int>(m_worlds.size()):static_cast<int>(SettingsState::ACTION_COUNT);m_menuController.scroll=std::clamp(m_menuController.scroll+(code==GLFW_KEY_PAGE_UP?-8:8),0,std::max(0,count-8));return;}
   if(code==GLFW_KEY_TAB||code==GLFW_KEY_UP||code==GLFW_KEY_DOWN){m_menuController.navigate(view,code==GLFW_KEY_UP||(code==GLFW_KEY_TAB&&(mods&GLFW_MOD_SHIFT))?-1:1);m_textTarget=0;if(m_menu==MenuState::Create&&!view.widgets.empty()){int id=view.widgets[m_menuController.focus].id;if(id==20||id==21)m_textTarget=id;}return;}
   int f=m_menuController.focus;if(f>=0&&f<static_cast<int>(view.widgets.size())&&view.widgets[f].enabled){auto& widget=view.widgets[f];if((code==GLFW_KEY_LEFT||code==GLFW_KEY_RIGHT)&&widget.value>=0){float step=widget.id==31?1.f/6:widget.id==32?1.f/60:1.f/99;slider(widget.id,widget.value+(code==GLFW_KEY_LEFT?-step:step));}else if(code==GLFW_KEY_ENTER||(code==GLFW_KEY_SPACE&&!m_textTarget))activate(widget.id);}return;
 }
 if(m_inventoryOpen){if(code==1000){double x,y;int ww,hh,fw,fh;glfwGetCursorPos(m_window,&x,&y);glfwGetWindowSize(m_window,&ww,&hh);glfwGetFramebufferSize(m_window,&fw,&fh);if(ww>0&&hh>0){float mx=static_cast<float>(x*fw/ww),my=static_cast<float>(y*fh/hh);auto hit=InventoryLayout::hitTest(mx,my,fw,fh,m_tableOpen,m_player.gameMode()==GameMode::Creative,m_furnaceOpen);if(hit.area!=InventoryLayout::Area::NONE||action==GLFW_RELEASE){inventoryMouse(mx,my,fw,fh,action);return;}}}if(action==GLFW_PRESS&&code==m_settings.key(KeyAction::Inventory))setInventoryOpen(false);return;}
 if(action==GLFW_PRESS&&m_captured){for(std::size_t i=0;i<SettingsState::ACTION_COUNT;++i)if(m_settings.key(static_cast<KeyAction>(i))==code&&m_input.justPressed(m_settings,static_cast<KeyAction>(i))){gameplayPress(code);break;}}
}
void Application::gameplayPress(int code){
 auto bound=[&](KeyAction a){return code==m_settings.key(a);};
 if(bound(KeyAction::Pause)){setMenu(MenuState::Pause);return;}if(bound(KeyAction::Inventory)){setInventoryOpen(true);return;}if(bound(KeyAction::Use)){useAction();return;}if(bound(KeyAction::ToggleHUD))m_hudVisible=!m_hudVisible;
 if(bound(KeyAction::OpenChat)){m_chatOpen=true;m_chatReady=false;m_chatEntry={};m_historyIndex=static_cast<int>(m_commandHistory.size());m_eating.cancel();m_sprint.cancel();syncCursor();return;}
 if(bound(KeyAction::ToggleFly)&&m_player.gameMode()==GameMode::Creative){m_player.toggleFly();m_sprint.cancel();m_eating.cancel();}if(bound(KeyAction::TogglePerspective))m_camera.cyclePOV();
 if(bound(KeyAction::Sprint)&&m_player.onGround&&!m_player.isFlying&&!m_player.isSneaking){m_eating.cancel();m_sprint.toggle();}if(bound(KeyAction::MoveForward)&&m_player.onGround&&!m_player.isFlying)if(m_sprint.forwardPressed(glfwGetTime()))m_eating.cancel();
 for(int i=0;i<9;++i)if(bound(static_cast<KeyAction>(static_cast<std::size_t>(KeyAction::Hotbar1)+i))){m_inventory.select(i);m_eating.cancel();}
 if(bound(KeyAction::PickBlock)){auto hit=Raycaster::cast(m_world,m_player.eyePosition(),m_player.forward(),6);if(hit.hit){auto type=m_world.getBlock(hit.block.x,hit.block.y,hit.block.z);for(int i=0;i<9;++i){const auto& item=m_inventory.hotbarSlot(i);if(!item.empty()&&item.kind==ItemKind::BLOCK&&item.blockType==type){m_inventory.select(i);return;}}for(int i=0;i<27;++i){auto item=m_inventory.backpackSlot(i);if(!item.empty()&&item.kind==ItemKind::BLOCK&&item.blockType==type){m_inventory.setBackpackSlot(i,m_inventory.selectedStack());m_inventory.setHotbarSlot(m_inventory.selectedSlot(),item);return;}}if(m_player.gameMode()==GameMode::Creative)m_inventory.setHotbarSlot(m_inventory.selectedSlot(),ItemStack::block(type,64));}}
 if(bound(KeyAction::DropItem)){auto item=m_inventory.selectedStack();if(!item.empty()){auto one=item;one.count=1;auto forward=m_player.forward();bool dropped=false;for(float distance:{.6f,.3f,0.f})if(m_renderer->throwDrop(m_player.eyePosition()+forward*distance,forward*4.f+glm::vec3(0,1,0),one,m_world)){dropped=true;break;}if(dropped){if(--item.count<=0)item={};m_inventory.setHotbarSlot(m_inventory.selectedSlot(),item);}else message("Cannot drop here or too many loose items");}}
}
void Application::message(const std::string& value){m_messages.push_back(value);if(m_messages.size()>100)m_messages.erase(m_messages.begin());m_chatScroll=0;m_notice=value;}
void Application::command(const std::string& entry){if(entry.empty())return;if(entry[0]!='/'){message(entry);return;}m_commandHistory.push_back(entry);if(m_commandHistory.size()>20)m_commandHistory.erase(m_commandHistory.begin());std::istringstream in(entry);std::string name,a,b,extra;in>>name;
 if(name=="/help"&&!(in>>extra)){message("/help | /gamemode survival|creative | /time set day|night | /tp x y z");return;}
 if(name=="/gamemode"&&(in>>a)&&!(in>>extra)&&(a=="survival"||a=="creative")){m_player.setGameMode(a=="creative"?GameMode::Creative:GameMode::Survival);m_sprint.cancel();m_eating.cancel();message("Game mode: "+a);return;}
 if(name=="/time"&&(in>>a>>b)&&!(in>>extra)&&a=="set"&&(b=="day"||b=="night")){if(b=="day")m_dayNight.skipToMorning();else m_dayNight.setTime(.75f);message("Time: "+b);return;}
 if(name=="/tp"){glm::vec3 p;if((in>>p.x>>p.y>>p.z)&&!(in>>extra)&&std::isfinite(p.x)&&std::isfinite(p.y)&&std::isfinite(p.z)&&p.x>=Player::WIDTH*.5f&&p.x<=1000-Player::WIDTH*.5f&&p.z>=Player::WIDTH*.5f&&p.z<=1000-Player::WIDTH*.5f&&p.y>=1&&p.y<=254){for(int x=static_cast<int>(p.x-.3f)/16;x<=static_cast<int>(p.x+.3f)/16;++x)for(int z=static_cast<int>(p.z-.3f)/16;z<=static_cast<int>(p.z+.3f)/16;++z)m_world.loadChunk(x,z);if(!PlayerPhysics::collides(m_player,p,m_world)){m_player.position=p;m_player.velocity={0,0,0};m_player.onGround=false;m_player.survival.resetFallDistance();m_player.clearMiningTarget();m_eating.cancel();m_sprint.cancel();m_input.suppress();message("Teleported");return;}}message("Unsafe or invalid teleport destination");return;}
 message("Unknown command or invalid arguments. Try /help");
}

MenuView Application::chatView()const{
 MenuView chat;chat.title="Local chat";std::vector<std::string> lines;
 for(const auto& message:m_messages)for(std::size_t pos=0;pos<message.size();pos+=100)lines.push_back(message.substr(pos,100));
 int end=std::max(0,static_cast<int>(lines.size())-m_chatScroll),start=std::max(0,end-12);
 for(int i=start;i<end;++i)chat.widgets.push_back({0,lines[i],160,130.f+(i-start)*32,960,28});
 std::string visible=m_chatEntry.display();if(visible.size()>100){auto begin=m_chatEntry.caret>95?m_chatEntry.caret-95:0;visible=visible.substr(begin,100);}
 chat.widgets.push_back({0,"> "+visible,160,560,960,44});chat.notice="Enter to send | Escape to cancel | Up / Down for commands | Wheel for messages";return chat;
}
